### PR TITLE
Fixes issue #10

### PR DESCRIPTION
**Pull request by bsrz**

### CODE REVIEW

**Comment by bsrz** [comment]
@ladanazita would it be possible to please merge this and create a beta4 tag?

**Comment by ladanazita** [comment]
Hey @bsarrazin ,

Thanks for the PR here. Just to summarize the issue here, the Segment-Optimizely-X SDK is using a variable that has been removed/changed in version 2.0+. 

To work around this, you are suggesting we pin a minimum version 1.5+. Can I ask why not 1.0, to include all version from 1 up to but not including 2?

**Comment by bsrz** [comment]
@ladanazita no reason in particular why 1.5
If you feel like including 1.0 is good enough for your needs, I can make the simple change.

**Comment by ladanazita** [comment]
My gut is to actually do the work to bump up to the latest (2.0). This does require a bit more work (since there are API changes).

For now, can you simply include the version you desire to use of Optimizely X in your podfile? Cocoapods will respect the version you pin over the dependency in Segment-Optimizely-X ( so long as it is > than what segment-optimizely-x pulls in)

Something like:

```
pod 'OptimizelySDKiOS', '~> 1.5'
pod 'Segment-Optimizely-X'
```

**Comment by jamesspittal** [comment]
Any update on this?

**Comment by atrivedi1** [comment]
@ladanazita, 

couple of follow up questions from the optimziely team:

1) Can you confirm that the suggested workaround will allow our joint clients to use Optimizely iOS SDK v2+? The PR thread seems to indicate that this approach only works for versions up to but not including 2. 
2) If so can you confirm that Segment has validated this approach on our v2 iOS SDK and would support this as a formal workaround?

**Pull request closed without merging**
